---
title: "SBTN State of Nature Water unified layers"
subtitle: "Prepare data to weight adm level aggregations"
author: "Rafael Camargo"
date: "Mar 21, 2024"
engine: knitr
format:
  html:
    toc: true
execute:
  warning: false    
---

## 1. Setup

Load required packages

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(here, dplyr, readr, sf, terra, raster, fasterize, purrr)
```

## 2. Load data

### 2.1. Water Consumption (pair with Water Depletion)

```{r}
wdp_basins <- read_sf(here("inputs", "water_depletion", "WaterGap3Shape", "WaterGap3_AllBasins.shp"))
```

```{r}
waterGap3_consumption <- read_csv(
  here("inputs", "water_depletion", "SectorConsumption_m3_annual.csv"),
  col_names = c("subBas_ID", "domestic", "manufacturing", "electric", "irrigation", "livestock")
)
```

## 3. Prepare data

### 3.1. Water Consumption (pair with Water Depletion)

```{r}
wdp_basins_consumption <- wdp_basins |> 
  dplyr::select(ContUID) |> 
  inner_join(waterGap3_consumption, by = c("ContUID" = "subBas_ID")) |> 
  mutate(
    industrial = manufacturing + electric,
    total = domestic + irrigation + livestock + industrial 
  ) |> 
  dplyr::select(
    dom = domestic,
    ind = industrial,
    irr = irrigation,
    liv = livestock,
    tot = total
  )
```

```{r}
fasterize_vars <- function(var){
  fasterize(wdp_basins_consumption, raster(wdp_basins_consumption, res = 0.01), field = var, fun = "max") |> 
    writeRaster(here("outputs", "raster", paste0("wdp_", var, ".tif")), overwrite = TRUE)
}
```

```{r}
map(list("dom", "ind", "irr", "liv", "tot"), fasterize_vars)
```



