---
title: "WRI Aqueduct data comparison"
subtitle: "what has changed between v3 and v4"
author: "Rafael Camargo"
date: "September 8, 2023"
engine: knitr
format:
  html:
    toc: true
execute:
  warning: false    
---

## 1. Setup

Load required packages

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, here, readxl, sf, skimr, rnaturalearth, mapview)
```

```{r}
sf::sf_use_s2(FALSE) # due to issues in HydroBASINS geometries
```

## 2. Load data

```{r}
onedrive_water <- "/Users/camargorafael/Library/CloudStorage/OneDrive-SharedLibraries-TheBostonConsultingGroup,Inc/Q-NC-Communities - Water"
```

```{r}
st_layers(here(onedrive_water, "4. Tools & Methods", "Aqueduct Water Risk Atlas", "Aqueduct 3.0", "baseline", "annual", "arcmap", "y2019m07d12_aqueduct30_v01.gdb"))
```

```{r}
v3 <- read_sf(here(onedrive_water, "4. Tools & Methods", "Aqueduct Water Risk Atlas", "Aqueduct 3.0", "baseline", "annual", "arcmap", "y2019m07d12_aqueduct30_v01.gdb"), layer = "annual")
```

```{r}
st_layers(here(onedrive_water, "4. Tools & Methods", "Aqueduct Water Risk Atlas", "Aqueduct 4.0", "GDB", "Aq40_Y2023D07M05.gdb"))
```

```{r}
v4 <- read_sf(here(onedrive_water, "4. Tools & Methods", "Aqueduct Water Risk Atlas", "Aqueduct 4.0", "GDB", "Aq40_Y2023D07M05.gdb"), layer = "baseline_annual")
```

```{r}
onedrive_data <- "/Users/camargorafael/Library/CloudStorage/OneDrive-SharedLibraries-TheBostonConsultingGroup,Inc/Q-NC-Communities - G3S/3. Data"
```

```{r}
son_water <- read_rds(here(onedrive_data, "sbtn", "sbtn_son_water.rds"))
```

## 3. Assess change in BWS from v3 to v4

```{r}
change <- v4 |>
  left_join(st_drop_geometry(v3), by = "aq30_id", suffix = c(".v4", ".v3"), keep = TRUE) |> 
  mutate(across(c(bws_raw.v4, bws_score.v4, bws_cat.v4), ~ na_if(.x, -9999))) |> 
  mutate(across(c(bws_cat.v3, bws_cat.v4), ~ if_else(.x == "Arid and Low Water Use", 5, .x))) |>  
  mutate(
    aq30_id.v4 = as.factor(aq30_id.v4),
    aq30_id.v3 = as.factor(aq30_id.v3),
    aq30_id.diff = ifelse(aq30_id.v3 == aq30_id.v4, FALSE, TRUE),
    name_0.diff = ifelse(name_0.v3 == name_0.v4, FALSE, TRUE),
    name_1.diff = ifelse(name_1.v3 == name_1.v4, FALSE, TRUE),
    bws_raw.diff = bws_raw.v4 - bws_raw.v3,
    bws_score.diff = bws_score.v4 - bws_score.v3,
    bws_cat.diff = bws_cat.v4 - bws_cat.v3,
    #bws_cat.diff = as.factor(bws_cat.diff),
    bws_label.v4 = na_if(bws_label.v4, "No Data"),
    bws_label.diff = ifelse(bws_label.v3 == bws_label.v4, FALSE, TRUE)
  ) |> 
  select(
    string_id.v4, aq30_id.v3, aq30_id.v4, aq30_id.diff,
    name_0.v3, name_0.v4, name_0.diff, name_1.v3, name_1.v4, name_1.diff,
    bws_raw.v3, bws_raw.v4, bws_raw.diff, bws_score.v3, bws_score.v4, bws_score.diff, bws_cat.v3, bws_cat.v4, bws_cat.diff, bws_label.v3, bws_label.v4, bws_label.diff
  )
```

```{r}
st_drop_geometry(change) |> 
  skim()
```

```{r}
change |>
  filter(bws_label.diff == TRUE) |>
  mutate(bws_cat.diff = as.factor(bws_cat.diff)) |> 
  mapview(
    layer.name = "Difference in BWS v3 to v4",
    zcol = "bws_cat.diff",
    col.regions = colorRampPalette(c("royalblue3", "grey95", "orangered3"))(10),
    lwd = 0,
    alpha.regions = 1
  )
```

```{r}
change |>
  st_drop_geometry() |> 
  filter(bws_label.diff == TRUE) |>
  count(bws_cat.diff, sort = TRUE)
```

```{r}
change |>
  st_drop_geometry() |> 
  filter(bws_label.diff == TRUE & bws_cat.diff %in% c(-5, -4, -3, 3, 4, 5)) |> 
  count(name_0.v4, sort = TRUE)
```

```{r}
change |>
  st_drop_geometry() |> 
  filter(bws_cat.diff > 0) |> # i.e, lower water stress than in v3
  nrow()/nrow(change)
```

## 4. Assess the effect on SBTN Water Availability layer

```{r}
son_water2 <- son_water |> 
  st_join(
    select(change, bws_raw2 = bws_raw.v4, bws_n2 = bws_cat.v4, bws_label2 = bws_label.v4),
    largest = TRUE
  ) |> 
  rowwise() |> 
  mutate(wa_max2 = max(c(bws_n2, wdp_n, wsb_n), na.rm = TRUE)) |> 
  ungroup() |> 
  mutate(
    wa_max.diff = wa_max2 - wa_max,
    wa_max.diff = if_else(!between(wa_max.diff, -5, 5), NA, wa_max.diff)
  ) |> 
  relocate(geometry, .after = last_col())
```

```{r}
son_water2 |> 
  st_drop_geometry() |> 
  skim()
```

```{r}
basemap <- ne_countries(scale = "medium", returnclass = "sf") |>
  filter(admin != "Antarctica")
```

```{r}  
data_for_plot <- son_water2 |>
  filter(wa_max.diff %in% c(-5:-1, 1:5)) |> 
  mutate(wa_max.diff = as.factor(wa_max.diff))
```

```{r} 
ggplot() +
  geom_sf(data = basemap, color = "grey50", fill = "grey95", lwd = 0.1, alpha = 1) +
  geom_sf(data = data_for_plot, aes(fill = wa_max.diff), color = "grey70", lwd = 0.01, alpha = 1) +
  geom_sf(data = basemap, color = "grey50", fill = NA, lwd = 0.1, alpha = 1) +
  scale_fill_manual(
    name = "Effect on SBTN layer\nMax Water Availability",
    limits = seq(-5, 5, 1),
    #values = colorRampPalette(c("royalblue4", "grey95", "orangered4"))(11)
    values = c(
      "-5" = "#27408B",
      "-4" = "#4F639F",
      "-3" = "#7887B4",
      "-2" = "#A0AAC8",
      "-1" = "#C9CEDD",
      "0" = "#F2F2F2",
      "1" = "#DDC8C1",
      "2" = "#C89F91",
      "3" = "#B47660",
      "4" = "#9F4E30",
      "5" = "#8B2500"
    )
  ) +
  coord_sf(
    xlim = c(-11800000, 15500000), # global view
    ylim = c(8200000, -6300000), # global view
    crs = "EPSG:8857",
    expand = FALSE
  ) +
  theme_void()
```

```{r}
ggsave(here("outputs", "Effect_on_SBTN_layer.jpeg"),
       width = 40, height = 20, dpi = 300, units = "cm", device = "jpeg")
```

```{r}
map_effect_son <- data_for_plot |>
  mapview(
    layer.name = "Effect on SBTN Water Availability layer",
    zcol = "wa_max.diff",
    col.regions = c("#27408B", "#4F639F", "#7887B4", "#A0AAC8", "#C9CEDD", "#DDC8C1", "#C89F91", "#B47660"),
    lwd = 0,
    alpha.regions = 1
  )
map_effect_son
```

```{r}
mapshot(map_effect_son, here("outputs", "Effect_on_SBTN_layer.html"))
```

```{r}
son_water2 |>
  st_drop_geometry() |> 
  filter(wa_max.diff %in% c(-5:-1, 1:5)) |>
  count(wa_max.diff, sort = TRUE)
```

```{r}
son_water2 |> 
  st_drop_geometry() |> 
  filter(wa_max.diff < 0) |> # i.e, lower wa_max than in v1 
  nrow()/nrow(son_water2)
```

```{r}
son_water2 |>
  st_drop_geometry() |> 
  filter(wa_max.diff > 0) |> # i.e, higher wa_max than in v1
  nrow()/nrow(son_water2)
```

## 5. Export 

```{r}
son_water2 |> 
  rename(wa_max.dif = wa_max.diff) |> 
  st_write(here("outputs", "shp", "sbtn_son_water_v2.shp"), layer_options = "ENCODING=UTF-8", delete_layer = TRUE)
```
